# 1. Жоба орындалатын негізгі Docker Image-ді таңдаймыз
image: node:20

# 2. Жұмыс кезеңдерін (stages) анықтаймыз
stages:
  - verify

# 3. Пакеттерді тез орнату үшін кэшті баптаймыз (Yarn cache)
cache:
  key:
    files:
      - yarn.lock
  paths:
    - .yarn-cache/
    - node_modules/

# 4. Негізгі жұмыстар басталмас бұрын орындалатын ортақ командалар (Мысалы, орнату)
before_script:
  - yarn install --frozen-lockfile --cache-folder .yarn-cache
  - yarn postinstall

# 5. Біздің тексеріс Job-ымыз
lint_and_type_check:
  stage: verify
  script:
    - yarn ts:fix
    - yarn lint
  # Қай тармақтарда (branches) ғана іске қосылу керектігін шектейміз
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "develop"'
